
TRUNCATE TABLE public.classrooms RESTART IDENTITY CASCADE;

TRUNCATE TABLE public.groups RESTART IDENTITY CASCADE;

TRUNCATE TABLE public.users RESTART IDENTITY CASCADE;

TRUNCATE TABLE public.courses RESTART IDENTITY CASCADE;

TRUNCATE TABLE public.lessons RESTART IDENTITY CASCADE;